// <auto-generated />
using System;
using KiemTraBuoi7.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiemTraBuoi7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605075524_AddAdminUser")]
    partial class AddAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KiemTraBuoi7.Models.ChiTietDangKy", b =>
                {
                    b.Property<int>("Madk")
                        .HasColumnType("int");

                    b.Property<string>("Mahp")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Madk", "Mahp");

                    b.HasIndex("Mahp");

                    b.ToTable("ChiTietDangKies");

                    b.HasData(
                        new
                        {
                            Madk = 1,
                            Mahp = "CNTT01"
                        },
                        new
                        {
                            Madk = 1,
                            Mahp = "CNTT02"
                        },
                        new
                        {
                            Madk = 2,
                            Mahp = "QTKD01"
                        },
                        new
                        {
                            Madk = 2,
                            Mahp = "QTKD02"
                        });
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.DangKy", b =>
                {
                    b.Property<int>("Madk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madk"));

                    b.Property<string>("Masv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayDk")
                        .HasColumnType("datetime2");

                    b.HasKey("Madk");

                    b.HasIndex("Masv");

                    b.ToTable("DangKies");

                    b.HasData(
                        new
                        {
                            Madk = 1,
                            Masv = "0123456789",
                            NgayDk = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Madk = 2,
                            Masv = "9876543210",
                            NgayDk = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.HocPhan", b =>
                {
                    b.Property<string>("Mahp")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Mahp");

                    b.ToTable("HocPhans");

                    b.HasData(
                        new
                        {
                            Mahp = "CNTT01",
                            SoTinChi = 3,
                            TenHp = "Lập trình C"
                        },
                        new
                        {
                            Mahp = "CNTT02",
                            SoTinChi = 2,
                            TenHp = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            Mahp = "QTKD01",
                            SoTinChi = 2,
                            TenHp = "Khởi sự và thương kệ"
                        },
                        new
                        {
                            Mahp = "QTKD02",
                            SoTinChi = 3,
                            TenHp = "Xác suất thống kê"
                        });
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.NganhHoc", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNganh");

                    b.ToTable("NganhHocs");

                    b.HasData(
                        new
                        {
                            MaNganh = "CNTT",
                            TenNganh = "Công nghệ thông tin"
                        },
                        new
                        {
                            MaNganh = "QTKD",
                            TenNganh = "Quản trị kinh doanh"
                        });
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.SinhVien", b =>
                {
                    b.Property<string>("Masv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Hinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Masv");

                    b.HasIndex("MaNganh");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            Masv = "admin",
                            CanLogin = false,
                            GioiTinh = "Nam",
                            Hinh = "/Content/images/admin.jpg",
                            HoTen = "Quản trị viên",
                            MaNganh = "CNTT",
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Masv = "0123456789",
                            CanLogin = false,
                            GioiTinh = "Nam",
                            Hinh = "/Content/images/sv1.jpg",
                            HoTen = "Nguyễn Văn A",
                            MaNganh = "CNTT",
                            NgaySinh = new DateTime(2000, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Masv = "9876543210",
                            CanLogin = false,
                            GioiTinh = "Nữ",
                            Hinh = "/Content/images/sv2.jpg",
                            HoTen = "Nguyễn Thị B",
                            MaNganh = "QTKD",
                            NgaySinh = new DateTime(2000, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.ChiTietDangKy", b =>
                {
                    b.HasOne("KiemTraBuoi7.Models.DangKy", "DangKy")
                        .WithMany()
                        .HasForeignKey("Madk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiemTraBuoi7.Models.HocPhan", "HocPhan")
                        .WithMany()
                        .HasForeignKey("Mahp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKy");

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.DangKy", b =>
                {
                    b.HasOne("KiemTraBuoi7.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("Masv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.SinhVien", b =>
                {
                    b.HasOne("KiemTraBuoi7.Models.NganhHoc", "MaNganhNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaNganhNavigation");
                });

            modelBuilder.Entity("KiemTraBuoi7.Models.NganhHoc", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
